spring:
  application:
    name: eurake-server
 
---
spring:
  profiles: eureka1

server:
  port: 2000
    
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:2000/eureka
    

  
---
spring:
  profiles: eureka2
  
server:
  port: 2001
  
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:2000/eureka
    
