spring:
  application:
    name: config-server
  profiles: 
    active:
    - native
    
  
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: admin
    password: admin
  
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config
#        git:
#          uri: https://github.com/nanbcdx/sh
#          searchPaths: config
#          username: nanbcdx
#          password: buxiaode1993
    
server:
  port: 5000
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2000/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
